version: "3"
# This compose will run an Express server along with an S3 server

services:
  file-upload-backend:
    # build: .
    image: api-local-backendserver:latest
    environment:
      S3SERVER: http://localhost:4569
    ports:
      - 5000:5000
    volumes:
      - .:/app
    restart: always

  localstack:
    image: localstack/localstack:1.0.4
    ports:
      - "4569:4569"
    environment:
      - SERVICES=s3:4569
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=us-east-2

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    volumes:
      - ./testbucket:/aws
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-2
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket my-bucket --region us-east-1
      "
